-- ============================================================
-- Aaya Perfume — the schema now lives in a versioned migration:
--
--     supabase/migrations/20260101000000_initial_schema.sql
--
-- Read that file instead of this one. It is applied automatically by
-- the Supabase GitHub integration every time `main` changes, so the
-- database can no longer drift away from the code.
-- ============================================================
--
-- If you are NOT using the GitHub integration, the migration file is
-- still plain Postgres: paste it into the Supabase SQL Editor (or a
-- Neon console) and press Run. Every statement is guarded with
-- "if not exists", so it is safe to run more than once.
--
-- To turn the integration on, see README section 3.